### ISSUE TITLE
Cosas que mejorar en AltaClienteUI y ParaAltaCliente

### ISSUE THREAD

**Issue by mariaProyectos** [marcofernandezheras/Fruteria#23]
AltaClienteUI:
-Mas margenes a la izquierda, derecha, arriba y MENOS margenes abajo.
-Que las cajas de texto ocupen hasta el margen.
-Boton de añadir cliente alineado por la derecha con las cajas de texto.
ParaAltaCliente:
-Controlar que no entren numeros en nombre, apellidos y color de pelo

**Comment by Danvgon** [comment]
Solo falta el ultimo punto por solucionar

**Comment by marcofernandezheras** [comment]
Arreglado
