### ISSUE TITLE
Cambios hechos en AltaArticuloUI y por hacer en ParaAltaArticulo

### ISSUE THREAD

**Issue by Danvgon** [marcofernandezheras/Fruteria#24]
Cambiado el PVP a no editable ya que dejaba editarlo.
No calcula el PVP automaticamente cuando introduces el precio ni cuando lo modificas.
No deberia dejar introducir numeros como nombre del articulo ni como descripcion del articulo (opinion personal)

**Comment by marcofernandezheras** [comment]
Arreglado por @MiguelHidalgo1991
