### ISSUE TITLE
ParaAltaPedido

### ISSUE THREAD

**Issue by MiguelHidalgo1991** [marcofernandezheras/Fruteria#48]
1- No se muestra el PVP
2- No se borra descripcion, precio, cantidad y me imagino que pvp cuando se muestre, cuando se añade una linea de pedido.
3- Se borra todos los datos del cliente al añadir linea
4- Cuando se busca y se encuentra el cliente, no se borran los campos de busqueda del cliente
5- Cuando se busca y no se encuentra el cliente, no se borran los datos del cliente anterior.
6- Cuando se busca un articulo que no existe, no se borra los datos del articulo anterior buscado y se pone el nombre del cliente a buscar en rojo.
7- Deja meter lineas de pedido con cantidad 0
8- Que en el total pedido se muestren solo dos decimalicos
9-!!!!  NULL POINTER EXCEPTION AL GUARDAR PEDIDO   !!!!! <3

**Comment by marcofernandezheras** [comment]
Fixed
